# Generated by Django 5.0.1 on 2024-02-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_instructor', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_pwd', models.CharField(max_length=20)),
                ('stu_email', models.CharField(max_length=50)),
                ('stu_course', models.CharField(max_length=100)),
                ('stu_role', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Studentmark',
            fields=[
                ('mark_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_id', models.CharField(max_length=20)),
                ('stu_name', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('assignment_1', models.CharField(max_length=20)),
                ('assignment_2', models.CharField(max_length=20)),
                ('assignment_3', models.CharField(max_length=20)),
                ('assignment_4', models.CharField(max_length=20)),
                ('assignment_5', models.CharField(max_length=20)),
                ('assignment_6', models.CharField(max_length=20)),
            ],
        ),
    ]
