# Generated by Django 5.0.1 on 2024-02-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='course_id',
            field=models.ForeignKey(default='default_course', on_delete=django.db.models.deletion.CASCADE, to='polls.courseinfo'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='stu_id',
            field=models.ForeignKey(default='default_student', on_delete=django.db.models.deletion.CASCADE, to='polls.studentinfo'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='stu_name',
            field=models.CharField(default='default_name', max_length=20),
        ),
    ]
