# Generated by Django 5.0.1 on 2024-02-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_studentmark_course_id_alter_studentmark_stu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='course_id',
            field=models.ForeignKey(default='default_course', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.courseinfo'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='stu_id',
            field=models.ForeignKey(default='default_student', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.studentinfo'),
        ),
    ]
