# Generated by Django 5.0.1 on 2024-02-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_studentinfo_stu_id_alter_studentmark_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmark',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentmark',
            old_name='stu_id',
            new_name='stu',
        ),
    ]
