# Generated by Django 5.0.1 on 2024-02-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_course_studentmark_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='course_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.courseinfo'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.studentinfo'),
        ),
    ]
