# Generated by Django 5.0.1 on 2024-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_studentmark_course_id_alter_studentmark_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='assignment_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='assignment_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='assignment_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='assignment_4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='assignment_5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='assignment_6',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
